require "recommendify/recommendify"
require "recommendify/base"
require "recommendify/sparse_matrix"
require "recommendify/cc_matrix"
require "recommendify/similarity_matrix"
require "recommendify/input_matrix"
require "recommendify/jaccard_input_matrix"
require "recommendify/cosine_input_matrix"
